version: '3.8'

services:
  web_gesp:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume_gesp:/home/gesp/web/staticfiles
      - media_volume_gesp:/home/gesp/web/mediafiles
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db_gesp
      - redis_gesp

  redis_gesp:
    image: redis:6.2-alpine
    #restart: always
    expose:
      - 6379
    command: redis-server

  db_gesp:
    image: postgres:13.8-alpine
    volumes:
      - postgres_data_gesp:/var/lib/postgresql/data/
    env_file:
      - .env

  nginx_gesp:
    build: ./nginx
    volumes:
      - static_volume_gesp:/home/gesp/web/staticfiles
      - media_volume_gesp:/home/gesp/web/mediafiles
    ports:
      - '1337:80'
    depends_on:
      - web_gesp

volumes:
  postgres_data_gesp:
  static_volume_gesp:
  media_volume_gesp: