# Generated by Django 4.1.2 on 2022-10-30 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inclusao', models.DateField(auto_now_add=True, verbose_name='Data de Inclusão')),
                ('hora_inclusao', models.TimeField(auto_now_add=True, verbose_name='Hora de Inclusão')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('hora_alteracao', models.TimeField(auto_now=True, verbose_name='Hora de Alteração')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inclusao', models.DateField(auto_now_add=True, verbose_name='Data de Inclusão')),
                ('hora_inclusao', models.TimeField(auto_now_add=True, verbose_name='Hora de Inclusão')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('hora_alteracao', models.TimeField(auto_now=True, verbose_name='Hora de Alteração')),
                ('tipo_origem', models.CharField(blank=True, choices=[('156', '156'), ('oficio', 'Ofício'), ('indicacao', 'Indicação')], max_length=15, null=True, verbose_name='Tipos de Origem')),
                ('numero_documento', models.CharField(blank=True, max_length=25, null=True, verbose_name='Número do Documento')),
                ('data_entrada', models.DateField(blank=True, null=True, verbose_name='Data de Entrada')),
                ('numero_endereco', models.CharField(blank=True, max_length=6, null=True, verbose_name='Número do Endereço')),
                ('informacao_extra_local', models.TextField(blank=True, null=True, verbose_name='Informação Extra do Local')),
                ('natureza_solicitante', models.CharField(blank=True, choices=[('municipe', 'Munícipe'), ('vereador', 'Vereador'), ('outros', 'Outros')], max_length=15, null=True, verbose_name='Natureza do Solicitante')),
                ('prazo_resposta', models.DateField(blank=True, null=True, verbose_name='Prazo para resposta')),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locais.endereco', verbose_name='Endereço')),
                ('tipo_servico', models.ForeignKey(blank=True, limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='solicitacoes.servicos', verbose_name='Tipo de servico')),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
                'ordering': ['-data_entrada', 'endereco__logradouro'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSolicitacao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_inclusao', models.DateField(blank=True, editable=False, verbose_name='Data de Inclusão')),
                ('hora_inclusao', models.TimeField(blank=True, editable=False, verbose_name='Hora de Inclusão')),
                ('data_alteracao', models.DateTimeField(blank=True, editable=False, verbose_name='Data de Alteração')),
                ('hora_alteracao', models.TimeField(blank=True, editable=False, verbose_name='Hora de Alteração')),
                ('tipo_origem', models.CharField(blank=True, choices=[('156', '156'), ('oficio', 'Ofício'), ('indicacao', 'Indicação')], max_length=15, null=True, verbose_name='Tipos de Origem')),
                ('numero_documento', models.CharField(blank=True, max_length=25, null=True, verbose_name='Número do Documento')),
                ('data_entrada', models.DateField(blank=True, null=True, verbose_name='Data de Entrada')),
                ('numero_endereco', models.CharField(blank=True, max_length=6, null=True, verbose_name='Número do Endereço')),
                ('informacao_extra_local', models.TextField(blank=True, null=True, verbose_name='Informação Extra do Local')),
                ('natureza_solicitante', models.CharField(blank=True, choices=[('municipe', 'Munícipe'), ('vereador', 'Vereador'), ('outros', 'Outros')], max_length=15, null=True, verbose_name='Natureza do Solicitante')),
                ('prazo_resposta', models.DateField(blank=True, null=True, verbose_name='Prazo para resposta')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('endereco', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locais.endereco', verbose_name='Endereço')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo_servico', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='solicitacoes.servicos', verbose_name='Tipo de servico')),
            ],
            options={
                'verbose_name': 'historical Solicitação',
                'verbose_name_plural': 'historical Solicitações',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalServicos',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_inclusao', models.DateField(blank=True, editable=False, verbose_name='Data de Inclusão')),
                ('hora_inclusao', models.TimeField(blank=True, editable=False, verbose_name='Hora de Inclusão')),
                ('data_alteracao', models.DateTimeField(blank=True, editable=False, verbose_name='Data de Alteração')),
                ('hora_alteracao', models.TimeField(blank=True, editable=False, verbose_name='Hora de Alteração')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('status', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical servicos',
                'verbose_name_plural': 'historical servicoss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
